services:
  back:
    container_name: sistema_estoque_backend
    build:
      context: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
  front:
    container_name: sistema_estoque_frontend
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
  db:
    container_name: sistema_estoque_db
    image: mysql:8
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_db_sistema_estoque:/var/lib/mysql
      - mysql_db_sistema_estoque_config:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      
    ports:
      - 8080:80

volumes:
  mysql_db_sistema_estoque:
  mysql_db_sistema_estoque_config:
